name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: npx lint-to-the-future output -o lttfOutput --rootUrl ember-cli-notifications --previous-results https://mansona.github.io/ember-cli-notifications/data.json
        working-directory: ember-cli-notifications
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ember-cli-notifications/lttfOutput
